### ISSUE TITLE
propagator.getPVCoordinates(minsAfterEpoch:) crash

### ISSUE THREAD

**Issue by NickRussell95** [gavineadie/SatelliteKit#4] opened 2022-07-26 16:22 UTC
### Summary
I am experiencing the following fatal error:

```Swift
SatKitError.SGP("ERROR 4: semi-latus rectum < 0.0")
``` 

When I try to calculate the position of the JWST using:

```Swift
Satellite.geoPosition(minsAfterEpoch:)
```

### Detail
I have the following TLE for JWST:

`0 JWST`
`1 50463U 21130A   21362.00000000  .00000000  00000-0  00000-0 0  9999`
`2 50463   4.6198  89.0659 9884983 192.3200  17.4027  0.01958082    27`

Which I fetched from [space-track.org](https://space-track.org)

I am constructing the Satellite like so:

```Swift
guard formatOK(TLE_LINE1, TLE_LINE2) else {
    throw TLEError.formatNotOkay
}
let elements = try Elements(TLE_LINE0, TLE_LINE1, TLE_LINE2)
let satellite = Satellite(elements: elements)
return satellite.geoPosition(minsAfterEpoch: 10)
```

Thanks for any help!

**Comment by NickRussell95** [comment] 2022-07-26 18:08
Upon further investigation this appears to be happening for any General Perturbation fetched from [space-track.org](https://space-track.org) where the `RCS_SIZE` is `null`.

For now, I can just exclude these Satellites from my data set and it appears to work. I'm not sure if this is intended?

**Comment by gavineadie** [comment] 2022-09-25 01:46
Apologies .. I've been away from this project for a while.  I'll take a look at this issue now.

**Comment by gavineadie** [comment] 2022-09-25 03:12
Quick comments, for now.

+ the `RCS_SIZE` value is not in the *3TLE* element format but it is in the *JSON* format. Are you reading the SpaceTrack *3TLE* or *JSON* format?
+ I ask because SpaceTrack changed their *JSON* encoding since I wrote my decoder and the new encoding will break my code.  I'll need to dig back a bit and see when SpaceTrack changed the encoding, and if there's a `version` flag I can use to distinguish between old and new. 
+ I can fix that easily but if you're not using the *JSON* (other than to filter out the `null` values of `RCS_SIZE`), I'll delay that till I find the cause of your (unrelated) problem.
+ if you're only using the *3TLE* lines, the problem isn't that `RCS_SIZE` is `null` (because that parameter doesn't appear in my code anywhere), although there must be a coincidental impact on one I **do** use.
+ The JWST elements are extreme (!), and I notice they've not changed since the end of July .. today's elements are the same as the ones you quoted.
+ I'm also going to make sure the JWST elements (in *3TLE* form) work in the original Vallado code.

More soon.

**Comment by gavineadie** [comment] 2022-09-25 03:46
> I'm also going to make sure the JWST elements (in 3TLE form) work in the original Vallado code.

I'll need to check my work tomorrow, it's late and I'm tired, but I don't think Vallado's 2006 code can cope with the JWST *3TLE* either, so this is a deeper problem, which doesn't mean it can't be solved!

**Comment by gavineadie** [comment] 2022-09-25 04:16
I took a look for any other web commentary about this and found:

https://space.stackexchange.com/questions/57771/does-the-james-webb-telescope-have-a-two-line-element-set

https://github.com/skyfielders/python-skyfield/issues/684

Both of which say TLEs are only useful for Earth orbiting objects, which JWST is not.  I'm going to close this because no propagator will make sense of the JWST TLEs and I can't fix that (!), but feel free to maintain any discussion/conversation about this ..

**Closed as completed by gavineadie** 2022-09-25 04:16 UTC
